#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

#set -e
set -x
exec > /tmp/tui-gen-log 2>&1

UNIT_DIR="${1:-/tmp}"

cmdline=( $(</proc/cmdline) )
cmdline_arg() {
    local name="$1" value="$2"
    for arg in "${cmdline[@]}"; do
        if [[ "${arg%%=*}" == "${name}" ]]; then
            value="${arg#*=}"
        fi
    done
    echo "${value}"
}

cmdline_bool() {
    local value=$(cmdline_arg "$@")
    case "$value" in
        ""|0|no|off) return 1;;
        *) return 0;;
    esac
}

add_requires() {
    local name="$1"; shift
    local target="$1"; shift
    local requires_dir="${UNIT_DIR}/${target}.requires"
    mkdir -p "${requires_dir}"
    ln -sf "../${name}" "${requires_dir}/${name}"
}


# This can't be done with ConditionKernelCommandLine because that always
# starts the unit's dependencies.
if $(cmdline_bool 'rd.net.tui' 0); then
    echo "noop" > /run/rd.net.tui
fi

# Run before the Ignition Targets
if $(cmdline_bool 'ignition.firstboot' 0); then
    add_requires net-tui.target ignition-complete.target
else
    add_requires net-tui.target ignition-subsequent.target
fi
